apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: serving
        metrics_path: /metrics
        static_configs:
          - targets: ["team-serving:8000"]
      - job_name: lama-serving
        metrics_path: /metrics
        static_configs:
          - targets: ["team-serving.lama.svc.cluster.local:8000"]
kind: ConfigMap
metadata:
  name: prom-config
  namespace: team
